CREATE TABLE [dbo].[Books]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	Title NVARCHAR(50) null,
	Year INT NULL,
	ISBN NVARCHAR(50) NOT NULL UNIQUE,
	Summary NVARCHAR(250) NULL,
	Price DECIMAL(18, 2) NULL,
	AuthorId INT NULL
	CONSTRAINT [FK_Books_ToTable] FOREIGN KEY ([AuthorId]) REFERENCES [Authors]([Id])
)
